# Model Configuration YAML
# Gold Price Prediction LSTM Model Hyperparameters

model:
  # LSTM Architecture
  lstm_units: [64, 32, 16]
  dropout_rate: 0.2
  recurrent_dropout: 0.2
  bidirectional: false
  attention: false
  
  # Dense layers
  dense_units: [32, 16]
  activation: 'relu'
  output_activation: 'linear'
  
  # Compilation
  optimizer: 'adam'
  learning_rate: 0.001
  loss: 'mse'
  metrics: ['mae', 'mse']

training:
  # Training parameters
  batch_size: 32
  epochs: 100
  validation_split: 0.2
  shuffle: false
  
  # Callbacks
  early_stopping:
    patience: 15
    min_delta: 0.0001
    restore_best_weights: true
  
  reduce_lr:
    patience: 7
    factor: 0.5
    min_lr: 0.0000001
  
  model_checkpoint:
    save_best_only: true
    save_weights_only: false
    monitor: 'val_loss'
    mode: 'min'

data:
  # Data preprocessing
  sequence_length: 60
  prediction_horizon: 1
  
  # Feature engineering
  lag_features: [1, 2, 3, 5, 7, 14, 30]
  moving_averages: [5, 10, 20, 50]
  technical_indicators:
    - sma
    - ema
    - rsi
    - macd
    - bollinger_bands
  
  # Normalization
  scaler_type: 'MinMaxScaler'
  feature_range: [0, 1]
  
  # Outlier detection
  outlier_method: 'iqr'
  outlier_threshold: 1.5

hyperparameter_tuning:
  # Search space
  lstm_units_range: [[32, 16], [64, 32], [128, 64], [64, 32, 16]]
  dropout_range: [0.1, 0.2, 0.3, 0.4]
  learning_rate_range: [0.0001, 0.001, 0.01]
  batch_size_options: [16, 32, 64]
  
  # Tuning settings
  n_trials: 50
  timeout: 3600  # 1 hour
  direction: 'minimize'
  metric: 'val_loss'

evaluation:
  # Metrics
  primary_metric: 'rmse'
  secondary_metrics: ['mae', 'mape', 'r2', 'direction_accuracy']
  
  # Cross-validation
  cv_folds: 5
  walk_forward_validation: true
  test_size: 0.2
  
  # Statistical tests
  significance_level: 0.05
  confidence_level: 0.95

prediction:
  # Forecasting
  forecast_horizon: 7
  confidence_intervals: [0.8, 0.9, 0.95]
  
  # Trend analysis
  trend_detection: true
  seasonality_detection: true
  
  # Anomaly detection
  anomaly_threshold: 2.0
  anomaly_method: 'isolation_forest'
